# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: prisma-cloud-compute-scan@1
  inputs:
    scanType: 'images'
    twistlockService: 'PC-Console-Scanner'
    vulnerabilityThreshold: 'low'
    onlyFixed: false
    gracePeriod: '0'
    complianceThreshold: 'low'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
